### ISSUE TITLE
salary dataset as dataset

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#1]
Currently both some vignettes and some examples run the following to get the `salary` data

```
salary <- read.table("http://www.emersonstatistics.com/datasets/salary.txt", header = TRUE, stringsAsFactors = FALSE)
```

This should instead be a documented dataset released with the package. 

This impact the vignette `regress_intro` amongst others.

**Comment by cwolock** [comment]
`salary`, `mri`, `psa`, and `fev` are now included in the package as fully documented datasets. All vignettes and examples (of functions that we're maintaining) have been changed accordingly.
