### ISSUE TITLE
Alternative hypothesis in ttest

### ISSUE THREAD

**Issue by jphughes9** [statdivlab/rigr#10]
The alternative hypothesis in test is specified with the argument "test.type". It would be better to be consistent with other R functions (particularly t.test) and use the argument "alternative". The attached version of ttest changes the
 argument name everywhere.
[my_ttest.txt](https://github.com/statdivlab/rigr/files/6353559/my_ttest.txt)

**Comment by taylorokonek** [comment]
The argument "alternative" is already used in the ttesti() function, so only the function ttest() needs to be updated. Updated print.ttest to be consistent with the 'alternative' argument as well. Added an informative error message if someone enters an invalid value into the 'alternative' argument and made a unit test to go with it.
