### ISSUE TITLE
Error in zzs$augCoefficients[u, ] <- zzs$coefficients 

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#103]
This issue comes up occasionally and I'm not sure what's causing it

```{r}
# none of these work
regress(fnctl = "rate", formula = deaths ~ gender + age + year, data=wonder, offset=log(pop), intercept = FALSE)
regress(fnctl = "rate", formula = deaths ~ gender + age + year - 1, data=wonder, offset=log(pop), intercept = FALSE)
regress(fnctl = "rate", formula = deaths ~ gender + age + year, data=wonder, offset=log(pop))
```

A temporary fix is to specify `as.numeric`

```{r}
regress(fnctl = "rate", formula = deaths ~ gender + age + as.numeric(year), 
        data=wonder, offset=log(pop))
regress(fnctl = "rate", formula = deaths ~ gender + age + as.numeric(year), 
        data=wonder, offset=log(pop), intercept = FALSE)
```

Note also that this issue comes up with `fnctl = "mean"` -- I will try to post some examples

**Comment by adw96** [comment]
Another fix/clue is to recenter year:

```
cdc %>% mutate(year_2010 = year - 2010) %>%
  regress("rate", deaths ~ gender + age + year_2010,
          offset = log(pop), data = .)
```

**Comment by yiqunchen** [comment]
@adw96 -- do you mind pointing me to the `wonder` data in the MWE -- cannot seem to find it in the package data files. Thanks!!

**Comment by adw96** [comment]
emailed instead 👍

**Comment by yiqunchen** [comment]
First of all, this bug is most likely due to the "conflict" between the predictor/covariate names `year` and `age` (which gives us `55-64 years`, `65-74 years`, `75-84 years`, and  `85+ years`. 

This logic has been updated in https://github.com/statdivlab/rigr/commit/6a57e1c7a3de7de4653e0378aa1b6233f0c427b7; lmk if you want to review this! @adw96.

The following test cases should work now.

```

wonder <- read.csv("~/Downloads/cdc-wonder-wa.csv")

test_1 <- regress(fnctl = "rate", 
        formula = deaths ~ gender + age + year, data=wonder, 
        offset=log(pop), intercept = FALSE)
test_2 <- regress(fnctl = "rate", formula = deaths ~ gender + age + year - 1, 
        data=wonder, offset=log(pop), 
        intercept = FALSE)
test_3 <- regress(fnctl = "rate", formula = deaths ~ gender + age + year, 
        data=wonder, offset=log(pop))
```

**Comment by adw96** [comment]
Terrific, thanks for the fix! What was the conflict? I don't imagine there's a colinearity issue...

**Comment by yiqunchen** [comment]
Aha my initial description was a bit vague -- essentially `regress` will create columns with names `55-64 years`, `65-74 years`, `75-84 years`, and  `85+ years` after recognizing that `age` as a categorical variable. However, the old version of the code was using `grep` loosely which will include all extra columns in creating `augCoefficients` for year..

The following should work on the old code (prior to https://github.com/statdivlab/rigr/commit/6a57e1c7a3de7de4653e0378aa1b6233f0c427b7), which indicates that it's likely not an issue about the data (colinear etc) but an issue about the variable names.

```
wonder %>% mutate(year_WTH = year) %>%
  regress("rate", deaths ~ gender + age + year_WTH,
          offset = log(pop), data = .)```

**Comment by adw96** [comment]
Fascinating! Thanks so much for tightening up the use of `grep`!
