### ISSUE TITLE
robust ANOVA 

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#104]
Would be great to have an implementation of stats's `anova()` that does robust F-tests. While often these tests can be wrangled with `U()`, it would be nice to have a format like 

```
test_submodel(null_model_regress_object, alternative_model_regress_object)
```

Most of the computational infrastructure for this already exists; the wrapper is the request.

**Comment by yiqunchen** [comment]
This feature has been implemented in the `anova` function (as of summer 2022).
