### ISSUE TITLE
Joint lincom tests

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#105]
Would be great to have a method for testing nulls of the form A \beta = c where A is k x p. Essentially this is a joint test version of `lincom`.

**Comment by yiqunchen** [comment]
This feature has been updated in https://github.com/statdivlab/rigr/commit/37647c21ccb2d80843b2517eba292d34fa7fa0fe; now the lincom takes a joint.test argument that specifies whether a joint or separate test should be conducted.
