### ISSUE TITLE
`regress` throws error when interactions with categorical variables have specified reference level

### ISSUE THREAD

**Issue by yiqunchen** [statdivlab/rigr#107]
`regress` throws an error for the following code:

data(mri)
regress("mean", atrophy ~ dummy(sex,reference="Male")*dummy(race), data = mri)

with the following error message
` Error in zzs$augCoefficients[u, ] <- zzs$coefficients : 
  number of items to replace is not a multiple of replacement length
In addition: Warning message:
In u[u] <- !droppedPred :
  number of items to replace is not a multiple of replacement length`.

I suspect the error is due to the fact that the current code cannot parse the interaction term with the `reference=` argument, but more investigation seems warranted.

Related to https://github.com/statdivlab/rigr/issues/69 and https://github.com/statdivlab/rigr/issues/67; and maybe related to https://github.com/statdivlab/rigr/issues/103 as well.

**Comment by adw96** [comment]
I unfortunately have no prior intel on this one, @yiqunchen, except that this error message comes up in a variety of settings (as you've already seen from the related bugs - nice work). 

The specification of the reference group in *both* `dummy`'s impacts the estimated intercept, and I wonder if this is accounted for in setting up the design matrix with a dummy x dummy model specification. My guess is that it's not and that a overparametrized model is fit... leading to a dimension mismatch. 

Happy to chat more about this on 7/18!

**Comment by adw96** [comment]
Also, this error seems pretty complicated, and the dummy x dummy setting hasn't come up yet, no need to address this urgently -- it can be an ongoing challenge to address. No need to burn yourself out with a hard one first 😸

**Comment by yiqunchen** [comment]
Great -- removing the high priority tag for now!

**Comment by yiqunchen** [comment]
resolved; test cases:
1. regress("mean", atrophy ~ dummy(sex,reference="Male")*dummy(race, reference="Black"), data = mri) 
2. egress("mean", atrophy ~ dummy(sex,reference="Male")*dummy(race, reference="White"), data = mri)
