### ISSUE TITLE
regress doesn't accept factors

### ISSUE THREAD

**Issue by jphughes9** [statdivlab/rigr#11]
Other regression commands in R accept factor covariates but
regress("mean", fev ~ ht+sex,data=fevdata)                    # fails if sex is a factor

**Comment by taylorokonek** [comment]
@jphughes9 could you send some code that recreates the error? I tried running 

regress("mean", fev ~ ht+factor(sex),data=fevdata) 

and it ran fine for me. Although the output looks a tad messy, but that should fall under issues #12 and #56

**Comment by jphughes9** [comment]
Taylor

Well, it is strange … see the example below. Am I doing something stupid? Dataset attached.

> fev <- read.table("G:/My Drive/Biost511_21/Datasets/fev.dat", quote="\"", comment.char="")
> names(fev)=c("id","age","fev","ht","sex","smoker")
> fev$fsex=factor(fev$sex)
> regress("mean", fev ~ ht+sex,data=fev)

Call:
regress(fnctl = "mean", formula = fev ~ ht + sex, data = fev)

Residuals:
    Min      1Q  Median      3Q     Max
-1.6763 -0.2505  0.0001  0.2347  2.0722

Coefficients:
                 Estimate  Naive SE   Robust SE
[1] Intercept     -5.390     0.1801     0.1932
[2] ht             0.1302   2.964e-03  3.247e-03
[3] sex            0.1251    0.03380    0.03201
                 95%L      95%H         F stat    df
[1] Intercept     -5.770    -5.011         778.48 1
[2] ht             0.1239    0.1366       1608.75 1
[3] sex           0.06227    0.1880         15.28 1
                 Pr(>F)
[1] Intercept    < 0.00005
[2] ht           < 0.00005
[3] sex             1e-04

Residual standard error: 0.4265 on 651 degrees of freedom
Multiple R-squared:  0.7587,      Adjusted R-squared:  0.758
F-statistic: 804.4 on 2 and 651 DF,  p-value: < 2.2e-16

> regress("mean", fev ~ ht+factor(sex),data=fev)

Call:
regress(fnctl = "mean", formula = fev ~ ht + factor(sex), data = fev)

Residuals:
    Min      1Q  Median      3Q     Max
-1.6763 -0.2505  0.0001  0.2347  2.0722

Coefficients:
                      Estimate  Naive SE   Robust SE
[1] Intercept          -5.390     0.1801     0.1932
[2] ht                  0.1302   2.964e-03  3.247e-03
[3]    factor(sex)      0.1251    0.03380    0.03201
                      95%L      95%H         F stat    df
[1] Intercept          -5.770    -5.011         778.48 1
[2] ht                  0.1239    0.1366       1608.75 1
[3]    factor(sex)     0.06227    0.1880         15.28 1
                      Pr(>F)
[1] Intercept         < 0.00005
[2] ht                < 0.00005
[3]    factor(sex)       1e-04

Residual standard error: 0.4265 on 651 degrees of freedom
Multiple R-squared:  0.7587,      Adjusted R-squared:  0.758
F-statistic: 804.4 on 2 and 651 DF,  p-value: < 2.2e-16

> regress("mean", fev ~ ht+fsex,data=fev)
Error in zzs$augCoefficients[u, ] <- zzs$coefficients :
  number of items to replace is not a multiple of replacement length
In addition: Warning message:
In u[u] <- !droppedPred :
  number of items to replace is not a multiple of replacement length

Jim
--------------
Jim Hughes
Professor of Biostatistics
University of Washington           Email: ***@***.******@***.***>
Mailstop 351617                           Phone: 206-616-2721
Seattle, WA  98195                        Fax:      206-616-2724
                                                          Cell:      206-498-2456

**Comment by taylorokonek** [comment]
that is.... very strange. thanks for the example, I can work with this now

**Comment by jphughes9** [comment]
Okay, glad to know it’s not just me 😊

Jim
--------------
Jim Hughes
Professor of Biostatistics
University of Washington           Email: ***@***.******@***.***>
Mailstop 351617                           Phone: 206-616-2721
Seattle, WA  98195                        Fax:      206-616-2724
                                                          Cell:      206-498-2456

**Comment by taylorokonek** [comment]
Alright the bug is fixed, `regress` should work now regardless of how you specify the factor. I need to address the coefficient names in the output still, but that's already listed in a separate issue (#56)
