### ISSUE TITLE
interaction terms in regress

### ISSUE THREAD

**Issue by jphughes9** [statdivlab/rigr#12]
# notice in the output of the following, the interaction term is not clearly labelled
# also the overall F-statistic from regress does not agree with the F-statistic from lm
regress("mean",fev~ht*as.integer(sex))

**Comment by taylorokonek** [comment]
@bdwilliamson a question for you on desired print output for `regress`. What was the intention in indenting certain coefficients in the output? As an example I've shown the coefficient names for regress("mean",fev~ht*sex) and regress("mean",fev~ht*as.integer(sex)) below.

regress("mean",fev~ht*sex):
[1] Intercept      
[2] height         
[3] sex             
[4] height:sex 

regress("mean",fev~ht*as.integer(sex)):
[1] Intercept           
[2] height               
[3]    integer(sex)     
[4]    integer(sex)

**Comment by taylorokonek** [comment]
oops it didn't appear above, but in the latter, both [3] and [4] are followed by indents before "integer(sex)" is printed

**Comment by bdwilliamson** [comment]
I think there were several reasons for indentation:
- derived variables (e.g., dummy variables, spline variables): to highlight that the variable of interest (e.g., smoking status) is different from the parameters estimated by the procedure (e.g., current smoker vs never smoker and past smoker vs never smoker)
- multiple-partial F-tests: to group variables desired for a multiple-partial F-test [e.g., U(~smoke + age)] to highlight that the *group* was tested together at the highest level; variable-specific results were indented

This issue appears to be a bug, where (perhaps) any function applied within the formula (as.integer in this case) is interpreted as either creating a derived variable or doing a multiple-partial F-test.

**Comment by taylorokonek** [comment]
Hi @jphughes9 ! A question for you. I'm finding that the F-statistic(s) returned from your code do align with what I would expect from normal R output (`lm` and then `sandwich`), when robust standard errors are used to calculate the t-statistic (and then square it to get the F-statistic). Were you comparing the t value (squared) to the rigr output directly? Those shouldn't necessarily align given that rigr is using robust things.

I agree that the labeling is bad, that's a work in progress at the moment.

**Comment by taylorokonek** [comment]
The indentation issue and labeling should look better now

**Comment by jphughes9** [comment]
Okay, I may not have been accounting for the robust standard errors

Jim
--------------
Jim Hughes
Professor of Biostatistics
University of Washington           Email: ***@***.******@***.***>
Mailstop 351617                           Phone: 206-616-2721
Seattle, WA  98195                        Fax:      206-616-2724
                                                          Cell:      206-498-2456

**Comment by taylorokonek** [comment]
Alright I think I'm going to go ahead and close this issue now then. I've written unit tests to ensure the f-statistic is correct in cases like this, and the output is clearly labeled, so moving forward this should be okay
