### ISSUE TITLE
Editorial comments on JOSS submission

### ISSUE THREAD

**Issue by osorensen** [statdivlab/rigr#138]
I'm reading through the [JOSS submission](https://github.com/openjournals/joss-reviews/issues/4847), and will post comments as issues in the repository.

My first comment is what you write on lines 66-67: "In the following example, we use regress to fit a linear regression model of atrophy (a measure of global brain activity assessed using MRI) on sex, weight, age, and race."

The part in the parentheses does not seem correct, since atrophy in fact is a measure of tissue loss. 

There are a few more things I don't understand about the example application starting on line 62:

- Is the atrophy measured by volume, area, or thickness?
- Is it cortical atrophy, averaged over the cerebral cortex, or does it also include subcortical volumes? 
- Atrophy is a measure of change, but estimating change requires at least two timepoints. What is then actually represented by the variable `atrophy` in the `mri` dataset?

I looked this up in the Kuller et al. (2007), and I wonder if what is actually represented by the `atrophy` variable is white matter grade? Could you please clarify, and if necessary update both the paper and the `mri` example dataset?

**Comment by yiqunchen** [comment]
Thanks for your detailed read and clarification! The MRI dataset was originally derived from Kuller et al. (2007) but has been adapted for the use of this package. 

In this case, atrophy is measured by the degree of ventricular enlargement relative to the predicted ventricular size; with 0 indicating no ventricular enlargement and 100 indicating the most severe degree of atrophy. 

We have clarified the text in the submission as follows:

In the following example, we use `regress` to fit a linear regression model of atrophy (a measure between 0 and 100 of global brain activity measured by the degree of ventricular enlargement relative to the predicted ventricular size; with 0 indicating no ventricular enlargement and 100 indicating the most severe degree of atrophy) on sex, weight, age, and race. 

Please let us know if you have any other questions; thank you again for your thorough review!

**Comment by osorensen** [comment]
Thanks for addressing this issue!

I'm still not completely on board, however, since the text still suggests that atrophy is a measure of global brain activity, which it is not. 

I suggest rewriting to the following:
> In the following example, we use regress to fit a linear regression model of atrophy (a measure between 0 and 100 of **loss of neurons estimated**  by the degree of ventricular enlargement relative to the predicted ventricular size; with 0 indicating no ventricular enlargement and 100 indicating the most severe degree of atrophy) on sex, weight, age, and race.

See, e.g., [here](https://www.ninds.nih.gov/health-information/disorders/cerebral-atrophy) or [here](https://www.britannica.com/science/atrophy).

**Comment by yiqunchen** [comment]
Thank you for your great suggestion! In this revision ([3ccb5a2](https://github.com/statdivlab/rigr/commit/3ccb5a24b50a119ae9bed03ad8c010d30a52c347)), we have edited the sentence to:

In the following example, we use `regress` to fit a linear regression model of atrophy (a measure of loss of neurons estimated by the degree of ventricular enlargement relative to the predicted ventricular size; with 0 indicating no atrophy and 100 indicating the most severe degree of atrophy) on sex, weight, age, and race. 

We really appreciate your reviews!

**Comment by osorensen** [comment]
Great! Could you please also update the documentation of the `atrophy` variable in `mri` dataset accordingly?

That is, here: https://github.com/statdivlab/rigr/blob/0d5f6eb2fa82bd80b3e41fadcdcb90a6694102eb/R/data.R#L95

**Comment by yiqunchen** [comment]
Thank you for your suggestion -- it has been revised accordingly in https://github.com/statdivlab/rigr/blob/main/R/data.R#:~:text=%27%20%5Citem%7Batrophy%7D%7Ba,degree%20of%20atrophy.%7D

**Comment by osorensen** [comment]
Thanks!
