### ISSUE TITLE
bplot axis label issue

### ISSUE THREAD

**Issue by jphughes9** [statdivlab/rigr#14]
# the followiong produces a plot with double x axis labels
bplot(fev,as.integer(agecat),xlab="Age Category",ylab="FEV (liters)")

**Comment by taylorokonek** [comment]
@jphughes9 can you send a link to the exact data you used here? I'm not seeing what the agecat variable is. This double x axis seems to occur in multiple settings however, so I'll begin working on it in the meantime

**Comment by jphughes9** [comment]
Taylor

Attached is the dataset. It is a Stata .dta file but can be read with the read.dta function in the foreign package

Jim
--------------
Jim Hughes
Professor of Biostatistics
University of Washington           Email: ***@***.******@***.***>
Mailstop 351617                           Phone: 206-616-2721
Seattle, WA  98195                        Fax:      206-616-2724
                                                          Cell:      206-498-2456

**Comment by taylorokonek** [comment]
@jphughes9 I'm not seeing the attached dataset

**Comment by taylorokonek** [comment]
found the error. bplot prints multiple x axis labels when the strata argument is used, and was incorrectly printing two x axis labels even when the strata argument is not used
