### ISSUE TITLE
intercepts in linear models

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#19]
If I recall correctly, you can use the argument `intercept = FALSE` in `regress()`. Is it possible to add the `-1`  functionality?

**Comment by taylorokonek** [comment]
Intercept removal can now be specified in two different ways:

1) intercept = FALSE
2) "-1" in the formula

If "-1" is in the formula _and_ intercept = FALSE is specified, the intercept will be removed. If a "-1" is in the formula and intercept = TRUE is specified, the intercept will still be removed.
