### ISSUE TITLE
remove `version` parameter from `descrip()`?

### ISSUE THREAD

**Issue by taylorokonek** [statdivlab/rigr#33]
Currently if you specify `version = TRUE` in `descrip()`, the function will return "20160730" and nothing else. I'd imagine we either want to to return a date that's a bit closer to today, or just remove this parameter entirely. Personally, I'm in favor of removing it entirely. Any objections or other thoughts?

**Comment by bdwilliamson** [comment]
I'm also in favor of removing it entirely. 

Something we could consider is adding a print message when the package gets loaded that says something about the version and/or the package creation date. For example of just printing the version and package title, see [here](https://github.com/bdwilliamson/vimp/blob/master/R/zzz.R); for example of including the date as well, see [here](https://github.com/ecpolley/SuperLearner/blob/master/R/zzz.R). Personally, I don't like the "package created on X date" message as much but could see it being nice if we have to change the package mid-quarter?

**Comment by taylorokonek** [comment]
New issue created to remove `version` parameter and change version info when package is loaded (#45)
