### ISSUE TITLE
Incorrect label in ttest

### ISSUE THREAD

**Issue by jphughes9** [statdivlab/rigr#34]
I downloaded the rigr package on 7/23 and was using ttest() and got this result. Notice  the incorrect label above the output that says "One-sample t-test"

> with(hiv,ttest(cd4[art==0],cd4[art==1]))

Call:
ttest(var1 = cd4[art == 0], var2 = cd4[art == 1])

Two-sample t-test allowing for unequal variances :
 

One-sample t-test :
 
Summary:
           Group Obs Missing  Mean Std. Err. Std. Dev.       95% CI
   cd4[art == 0]  78      14 388.5      32.5       260 [323.5, 454]
   cd4[art == 1]  50      19 298.5      32.9       183 [231.3, 366]
      Difference 128      33  90.1      46.3      <NA> [-2.02, 182]

 Ho: difference in  means = 0 ; 
 Ha: difference in  means != 0 
 t = 1.946 , df = 80.7 
 Pr(|T| > t) =  0.0551195

**Comment by cwolock** [comment]
Fixed as of d650c529535dc28353c78099aadf986bcba7b339
