### ISSUE TITLE
why does `regress` no longer support proportional hazards regression, and what do we want moving forward?

### ISSUE THREAD

**Issue by taylorokonek** [statdivlab/rigr#35]
The documentation for `regress` seems to suggest you can do proportional hazards regression using fnctl = "hazard", but the code will actually throw an error if you specify fnctl = "hazard", stating "proportional hazards regression no longer supported". That being said, the remainder of the code seems to still have if/else cases and other sections in case fnctl = "hazard", so is this error something that was thrown in recently? @bdwilliamson do you have any insight?

Another question is whether we want `regress` to be able to handle proportional hazards regression moving forward.

**Comment by bdwilliamson** [comment]
This is actually the reason that `uwIntroStats` got pulled from CRAN -- the authors of the `survival` package made a breaking change that we didn't have support/time to fix. 

I think it's worth a higher-level discussion for all things `regress` (referencing this issue).

**Comment by taylorokonek** [comment]
Ah I see. Definitely worth a higher-level discussion then.

**Comment by taylorokonek** [comment]
Discussion thread started here: #36
