### ISSUE TITLE
changed behavior for descrp

### ISSUE THREAD

**Issue by jphughes9** [statdivlab/rigr#50]
The newest version of descrip prints, by default, the columns Max Restriction, FirstEvent, LastEvent, isDate. Those seem confusing for the average user, especially if none of the measures is a time-to-event. Can we have descrip not print those columns by default?

Also, at the bottom of the descrip output I see 
attr(,"class")
[1] "uDescriptives"
which will be confusing to the naive user. 

Finally, all statistics are printed in scientific notation which is different from before and harder to read.

Having said all this, I just figured out that I think the issue is simply that the print.uDescriptives function has not been included in the rigr package?

**Comment by cwolock** [comment]
I haven't really touched `descrip` but I do know that most of the `print` methods were, for some reason, not exported. I had to fix this for `wilcoxon`, for example. Should be an easy solution.

**Comment by taylorokonek** [comment]
This should be fixed now! @jphughes9 if you want to test it out again to see if the newest version looks good to you, that would be great

**Comment by jphughes9** [comment]
Yes, fixed!

Jim
--------------
Jim Hughes
Professor of Biostatistics
University of Washington           Email: ***@***.******@***.***>
Mailstop 351617                           Phone: 206-616-2721
Seattle, WA  98195                        Fax:      206-616-2724
                                                          Cell:      206-498-2456
