### ISSUE TITLE
`proptest`

### ISSUE THREAD

**Issue by cwolock** [statdivlab/rigr#58]
Implement `proptest` function as a branch from `ttest`. Add continuity correction, which is not currently implemented.

**Comment by jphughes9** [comment]
@cwolock Will this version of proptest have an "EXACT" option that will allow it to also reproduce the results of binom.test?

**Comment by cwolock** [comment]
to-do: Allow non-zero difference on means in two-sample test. Continuity correction. Work with factors or binary numeric data that not 0-1?

**Comment by cwolock** [comment]
function documentation

**Comment by cwolock** [comment]
All of the above are finished except for continuity correction.

**Comment by cwolock** [comment]
Continuity correction implemented
