### ISSUE TITLE
wilcoxon returns 1-sided p-value for Z when it says 2-sided

### ISSUE THREAD

**Issue by jphughes9** [statdivlab/rigr#63]
Wilcoxon rank sum test 
         obs rank sum expected
Y         10       78    175.5
X         16      273    175.5
combined  26      351    351.0
                               
unadjusted variance 360.0000000
adjustment for ties   0.1015385
adjusted variance   359.8984615
                    H0 Ha       
Hypothesized Median 0  two.sided
  Test Statistic p-value 
W 137            0.002614
Z 3.0098         0.001307

**Comment by cwolock** [comment]
Could you post the code that gave you this output? Sorry about this - I'm not sure how this one slipped through unit testing...

**Comment by jphughes9** [comment]
seropos = c(2.9,12.1,2.6,2.5,2.8,15.8,3.2,1.8,7.8,2.9,3.2,8.0,1.5,6.3,1.2,3.5)
seroneg = c(4.5,1.3,1.0,1.0,1.3,1.9,1.3,2.1,2.1,1.0)
wilcoxon(seropos,seroneg)

**Comment by jphughes9** [comment]
Very strange. I had just installed rigr 30 minutes ago and got that error. But upon reinstalling it seems to work fine!

Jim
--------------
Jim Hughes
Professor of Biostatistics
University of Washington           Email: ***@***.******@***.***>
Mailstop 351617                           Phone: 206-616-2721
Seattle, WA  98195                        Fax:      206-616-2724
                                                          Cell:      206-498-2456

**Comment by cwolock** [comment]
Hmmm, okay. Well, I'm going to close the issue for now. If it happens again let me know.
