### ISSUE TITLE
bug in ttesti

### ISSUE THREAD

**Issue by jphughes9** [statdivlab/rigr#8]
one-sided p-value in ttesti wrong for Ha: <. Fixed in the attached file (to find changes, search for "JPH")
[my_ttesti.txt](https://github.com/statdivlab/rigr/files/6353520/my_ttesti.txt)

**Comment by cwolock** [comment]
This bug is fixed. However, it still needs a unit test. I'm going to wait until after changing `ttesti()` to return an object - this will make unit test easier rather than having to parse a string.

**Comment by cwolock** [comment]
Bug fix confirmed in unit testing.
