### ISSUE TITLE
CRAN submission punch list

### ISSUE THREAD

**Issue by cwolock** [statdivlab/rigr#81]
Check all function documentation and examples
Check `DESCRIPTION`
Update `rigr-package`
Update `README`
Check `LICENSE`
Print version when loaded

**Comment by cwolock** [comment]
`cran-comments.md`

**Comment by taylorokonek** [comment]
Updated `rigr-package.R`, but it may need to be updated again with a version number (not sure if we have that yet?). I set the date in that file to 2021-09-10, which is the date we plan on submitting to CRAN, but that may need to be updated as well

**Comment by taylorokonek** [comment]
`README` has been updated

**Comment by cwolock** [comment]
Added `cran-comments.md` - make sure this is up-to-date just before we submit

**Comment by taylorokonek** [comment]
version number should now be printed when package is attached

**Comment by cwolock** [comment]
I updated `rigr-package.R` with version 1.0.0
