### ISSUE TITLE
sex & smoke to characters in fev

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#82]
Hi Charlie & Taylor -- I'm just reviewing the package now, including the vignettes, and it looks fantastic. A short request: could we please change the variables `sex` & `smoke` to characters in `fev` to remove ambiguity about `1` and `2`?  It will make things much easier for our students, and if they want to recode then they can. 

This change should affect the dataset and also its description. 

I took a quick look at the other datasets and think that `fev` is the only dataset with this feature. 

Thank you both!

**Comment by cwolock** [comment]
Done!
