### ISSUE TITLE
wilcoxon with conf.int = TRUE triggers warning (intentional but the wrong outlet?)

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#83]
From the one and two sample inference vignette: 

```
cf <- c(1153, 1132, 1165, 1460, 1162, 1493, 1358, 1453, 1185, 1824, 1793, 1930, 2075)
healthy <- c(996, 1080, 1182, 1452, 1634, 1619, 1140, 1123, 1113, 1463, 1632, 1614, 1836)
wilcoxon(cf, healthy, paired = TRUE, conf.int = TRUE)
```

produces the warning "The 'confidence interval' presented is semi-parametric and non-robust, and is a test of medians." (from `print.wilcoxon()`) 

While true, I don't believe that this should be a `R` warning. 

A non exhaustive list of our options include
1. keeping the warning (possibly with implications for CRAN - I doubt the CRAN overlords like vignettes triggering warnings!)
2. printing that text at the bottom of a printed `wilcoxon` object
3. removing that note entirely

(3) is most in the spirit of this package and its vignettes ("here is how to do it; please refer to your stats class on why and when"), but (2) better honours the spirit of the package creators and their views on nonparametric tests. 

Thoughts from others?

**Comment by cwolock** [comment]
I agree it shouldn't be a proper warning. 

I'd be curious to hear what  @jphughes9 thinks about this re how he teaches Wilcoxon and Mann-Whitney tests in 511 (which is the only class I've TA'ed). I imagine the message as written is probably pretty confusing for 511 students at least - I don't think semiparametrics are really presented in that class.

**Comment by jphughes9** [comment]
I agree it shouldn't be a warning. In fact, I would go with option 3 and just document the characteristics of the CI in the function documentation. Two other comments - I don't even cover CI for medians in 511; the term "test of medians" in the description of the CI seems a bit off ... maybe better to say "comparison of medians"?

**Comment by cwolock** [comment]
Okay, got rid of the warning and added a note to the docs explaining what the confidence intervals are for.
