### ISSUE TITLE
Question about multiple categorical variables in `regress`

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#84]
Hi @taylorokonek ! I'm looking through the regression vignette (so great!), and was comparing the format of the output of 

`regress("mean", atrophy ~ age + sex, data = mri)` 

which includes `sexMale` as the name of a estimated coefficient, with that of 

`regress("mean", atrophy ~ age + sex + race, data = mri)`

for which the name of an estimated coefficient is just `sex`.

Would it be possible to have the name of the estimated coefficient in the second model to also be `sexMale`?  I presume the difference is triggered by the inclusion of another categorical variable in the model, but I appreciate the transparency in the first model's output.

**Comment by adw96** [comment]
Curious but good: `regress("mean", atrophy ~ age + sex + U("Smoking variables" = ~packyrs + yrsquit), data = mri)` includes the variable `sexMale` 👍

**Comment by taylorokonek** [comment]
This should be fixed now, @adw96 if you want to confirm that the output looks as it should that would be great!

**Comment by adw96** [comment]
Thanks @taylorokonek ! LGTM!
