### ISSUE TITLE
Including information about links for GLMs

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#85]
Hi @taylorokonek - could you please confirm the correctness of the following statement:

"Note that the only possible link function in `regress` with `fnctl = odds"` is the logit link. Similarly, the only possible link function in `regress` with `fnctl = "rate"` is the log link."

I'm just adding some notes in the documentation and vignettes about GLM links and want to be sure this is right. Thanks! 

(Thought it would be easier to check this here rather than asking for a full code review on a PR)

**Comment by taylorokonek** [comment]
Yes, that's correct! Only those links work with those `fnctl`s, respectively

**Comment by adw96** [comment]
Wonderful, thank you so much!
