### ISSUE TITLE
confirm descriptions up to date

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#89]
Hi @statdivlab/rigr-ta-team - could you please both review the descriptions of all functions now included in the package to make sure that they are up to date? The below is the first paragraph is regress, but I don't think `Surv` objects are permitted it any more. 

```
#' Produces point estimates, interval estimates, and p values for an arbitrary
#' functional (mean, geometric mean, proportion, odds) of a
#' variable of class \code{integer}, \code{numeric}, \code{Surv}, when
#' regressed on an arbitrary number of covariates. Multiple Partial F-tests can
#' be specified using the \code{\link[rigr]{U}} function.
```

Could someone also please do a search for "estimating equations", "Cox", "proportional hazards", and any other functionality that we axed just to make sure that there aren't any more lingering references to this?

Many thanks!

**Comment by taylorokonek** [comment]
`regress` and `descrip` have been updated, and should be good to go. I'll check on the estimating equations / gee / cox / proportional hazards things

**Comment by taylorokonek** [comment]
No lingering references to any of the above mentioned

**Comment by cwolock** [comment]
I checked `ttest`, `ttesti`, `proptest`, `proptesti`, `wilcoxon`, and `lincom`. I also did a search for "gee", "survival", "hazard", estimating equations", etc. in the full package. I don't think there are any references where there shouldn't be.
