### ISSUE TITLE
other functions that can go in a regress formula

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#91]
A request for @taylorokonek -- in the documentation for `regress` under the argument `formula` (currently reads "an object of class formula as might be passed to lm, glm, or coxph."), could you please also include a list of other `rigr` functions that can go in a formula? eg `dummy()`, `polynomial()`, etc. (This was where I went looking for the answer to #90, and this might be useful for others as well). 

Thank you -- I very much appreciate your `regress` expertise!

**Comment by taylorokonek** [comment]
Update this (and removed the mention of coxph)
