### ISSUE TITLE
typo in `README`

### ISSUE THREAD

**Issue by cwolock** [statdivlab/rigr#95]
Amy,

I think there might be a typo due to the last change pushed to the `README` - it says "you can install the development version from CRAN..." I think maybe it should say "stable version" or something like that? I would change it myself but I'm not sure if you're just about to submit everything.

**Comment by adw96** [comment]
Thanks Charlie! Actually I fixed this in `9f2cece` -- you must have looked in between when I was making the package CRAN-ready and updating it to send out an email to the department. Hopefully it looks ok right now?

**Comment by cwolock** [comment]
Yes, looks good!
