### ISSUE TITLE
Post estimation plots

### ISSUE THREAD

**Issue by orvaquim** [statdivlab/rigr#96]
It would be great if few post-estimation plots would be added for:
- GOF 
- Display the coefficients plots: with/without the Intercept, and exponentiated/not exponentiated.

at least. Yes, there are a few packages to do that but they cannot work with a uRegress object without a bit challenging code (for a R newcomer).

**Comment by adw96** [comment]
Thanks for using the package, @orvaquim. Could you please provide some more details on what you're looking for? For example, what is the package and function that displays your "coefficient plots" for a regular `lm` object -- my apologies, but I haven't heard this term before. 

What goodness of fit plots are you interested in?

Once I have a better idea of what you're after I'll be able to determine if it's feasible with current resources.

**Comment by adw96** [comment]
(closed pending details)
