### ISSUE TITLE
clarify documentation regarding where CIs come from

### ISSUE THREAD

**Issue by adw96** [statdivlab/rigr#99]
It took me an embarrassingly long time today to figure out whether the confidence intervals use robust SEs or classical SEs by default 😊  (they use robust, at least for "mean"). 

I wish this was labeled more clearly in the documentation -- could be an easy fix next time someone does a commit of any sort.
 
The code was actually kind of opaque to me (`SEcol <- ifelse(dimnames(x)[[2]][3]=="RobustSE",3,2)` in line 1699 of `regress_utils.R` 🤯 ) and it was easier to figure this out with an example. (Below in case I need it again.)

```{r}
set.seed(1)
x <- 1:40
y <- rnorm(40, mean=x, sd = x)
plot(x,y)
reg1 <- regress("mean", y ~ x, data = tibble(y, x))
round(c((reg1 %>% coef)[1,1]+qnorm(0.975)*(reg1 %>% coef)[1,3] ,
        (reg1 %>% coef)[1,1]+qnorm(0.975)*(reg1 %>% coef)[1,2] ,
        (reg1 %>% coef)[1,1]+qt(0.975,38)*(reg1 %>% coef)[1,2] ,
        (reg1 %>% coef)[1,1]+qt(0.975,38)*(reg1 %>% coef)[1,3] ), 3) ## winner
reg1 #  9.378    
```

**Comment by yiqunchen** [comment]
Proposal: update the documentation for the robustSE to be "robustSE: a logical indicator that standard errors **(and confidence intervals)** are to be computed using the Huber-White sandwich estimator."

**Comment by adw96** [comment]
Terrific! Is the default listed for `robustSE`? Might be good to state explicitly in the docs. 

Thanks, @yiqunchen !!! 🙌

**Comment by yiqunchen** [comment]
The documentation has been updated in the latest version; closing the issue.
